apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roadmap-web
  name: roadmap-web
  namespace: default
spec:
  progressDeadlineSeconds: 100
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: roadmap-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: roadmap-web
    spec:
      containers:
        - image: ${ROADMAP_WEB_IMAGE_TAG}
          imagePullPolicy: Always
          name: roadmap-web
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: roadmap-web-svc
  namespace: default
  labels:
    app: roadmap-web-svc
spec:
  ports:
    - name: port
      port: 40004
      protocol: TCP
      targetPort: 80
  selector:
    app: roadmap-web
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/service-weight: ''
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  name: road-ingress
  namespace: default
spec:
  rules:
    - host: ${DOMAIN-1}
      http:
        paths:
          - backend:
              service:
                name: roadmap-web-svc
                port:
                  number: 40004
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: roadmap-java-svc
                port:
                  number: 40012
            path: /api
            pathType: ImplementationSpecific
          - backend:
              service:
                name: roadmap-java-svc
                port:
                  number: 40012
            path: /base
            pathType: ImplementationSpecific
    - host: ${DOMAIN-2}
      http:
        paths:
          - backend:
              service:
                name: roadmap-web-svc
                port:
                  number: 40004
            path: /
            pathType: ImplementationSpecific
          - backend:
              service:
                name: roadmap-java-svc
                port:
                  number: 40012
            path: /api
            pathType: ImplementationSpecific
          - backend:
              service:
                name: roadmap-java-svc
                port:
                  number: 40012
            path: /base
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ${DOMAIN-1}
      secretName: ${DOMAIN-1-TLS}
    - hosts:
        - ${DOMAIN-2}
      secretName: ${DOMAIN-2-TLS}

